import pygame
import math
pygame.init()

# sizes
WIDTH = 1280
HEIGHT = 720

ZOOM = (WIDTH + HEIGHT) / 1000

# text and GUI
DIALOG_BOX_WIDTH = ((WIDTH / 1.28) * 7) / 10
DIALOG_BOX_HEIGHT = HEIGHT / 7.2

DIALOG_BOX_X_POSITION = DIALOG_BOX_WIDTH / 2
DIALOG_BOX_Y_POSITION = HEIGHT - DIALOG_BOX_HEIGHT

DIALOG_PORTRAIT_X_POSITION = DIALOG_BOX_X_POSITION - DIALOG_BOX_HEIGHT
DIALOG_PORTRAIT_Y_POSITION = DIALOG_BOX_Y_POSITION

DIALOG_BOX_COLOR = (19.2, 21.2, 22)

FONT_SIZE = math.ceil((WIDTH + HEIGHT) / (2000 / 18))

# miscellaneous
FPS = 60
